[workspace]
resolver = "3"
members = [
    "rust/core",
    "rust/capture",
    "rust/input",
    "rust/windows",
    "rust/accessibility",
    "rust/vision",
    "rust/desktop",
    "rust/ipc",
    "rust/plugins",
    "rust/daemon",
    "cli",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nordbyte/PeekabooX"
version = "1.0.1"
