# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from peekaboox.v1 import peekaboox_pb2 as peekaboox_dot_v1_dot_peekaboox__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peekaboox/v1/peekaboox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeekabooXStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScreen = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/CaptureScreen',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenResponse.FromString,
                _registered_method=True)
        self.CaptureDelta = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/CaptureDelta',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaResponse.FromString,
                _registered_method=True)
        self.CaptureBackends = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/CaptureBackends',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsResponse.FromString,
                _registered_method=True)
        self.MoveMouse = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/MoveMouse',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.MoveMouseRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/Click',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ClickRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Drag = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/Drag',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DragRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/TypeText',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.TypeTextRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.PasteText = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/PasteText',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.PasteTextRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Hotkey = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/Hotkey',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.HotkeyRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.FindElement = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/FindElement',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.FindElementRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.FindElementResponse.FromString,
                _registered_method=True)
        self.ListWindows = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/ListWindows',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsResponse.FromString,
                _registered_method=True)
        self.GetDesktopState = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/GetDesktopState',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.GetDesktopStateRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopState.FromString,
                _registered_method=True)
        self.OcrScreen = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/OcrScreen',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.OcrScreenRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.OcrResponse.FromString,
                _registered_method=True)
        self.CompareImages = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/CompareImages',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CompareImagesRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.VisualDiffResponse.FromString,
                _registered_method=True)
        self.DetectUiState = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DetectUiState',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiStateRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.UiStateResponse.FromString,
                _registered_method=True)
        self.DetectUiElements = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DetectUiElements',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsResponse.FromString,
                _registered_method=True)
        self.ProbeDmaBuf = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/ProbeDmaBuf',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ProbeDmaBufRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DmaBufProbeResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/ListPlugins',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.PluginListResponse.FromString,
                _registered_method=True)
        self.CallPluginTool = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/CallPluginTool',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CallPluginToolRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.PluginToolExecutionResponse.FromString,
                _registered_method=True)
        self.DesktopFocus = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopFocus',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopFocusRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
                _registered_method=True)
        self.DesktopLocate = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopLocate',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateResponse.FromString,
                _registered_method=True)
        self.DesktopClick = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopClick',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopClickRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
                _registered_method=True)
        self.DesktopDrag = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopDrag',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopDragRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
                _registered_method=True)
        self.DesktopTypeInto = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopTypeInto',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopTypeIntoRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
                _registered_method=True)
        self.DesktopAssert = channel.unary_unary(
                '/peekaboox.v1.PeekabooX/DesktopAssert',
                request_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopAssertRequest.SerializeToString,
                response_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
                _registered_method=True)


class PeekabooXServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CaptureScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureBackends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveMouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PasteText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hotkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDesktopState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OcrScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectUiState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectUiElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeDmaBuf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallPluginTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopFocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopLocate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopClick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopDrag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopTypeInto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesktopAssert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeekabooXServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenResponse.SerializeToString,
            ),
            'CaptureDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureDelta,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaResponse.SerializeToString,
            ),
            'CaptureBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureBackends,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsResponse.SerializeToString,
            ),
            'MoveMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveMouse,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.MoveMouseRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ClickRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'Drag': grpc.unary_unary_rpc_method_handler(
                    servicer.Drag,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DragRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.TypeTextRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'PasteText': grpc.unary_unary_rpc_method_handler(
                    servicer.PasteText,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.PasteTextRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'Hotkey': grpc.unary_unary_rpc_method_handler(
                    servicer.Hotkey,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.HotkeyRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.SerializeToString,
            ),
            'FindElement': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElement,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.FindElementRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.FindElementResponse.SerializeToString,
            ),
            'ListWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWindows,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsResponse.SerializeToString,
            ),
            'GetDesktopState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDesktopState,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.GetDesktopStateRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopState.SerializeToString,
            ),
            'OcrScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.OcrScreen,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.OcrScreenRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.OcrResponse.SerializeToString,
            ),
            'CompareImages': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareImages,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CompareImagesRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.VisualDiffResponse.SerializeToString,
            ),
            'DetectUiState': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectUiState,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiStateRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.UiStateResponse.SerializeToString,
            ),
            'DetectUiElements': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectUiElements,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsResponse.SerializeToString,
            ),
            'ProbeDmaBuf': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbeDmaBuf,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ProbeDmaBufRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DmaBufProbeResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.ListPluginsRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.PluginListResponse.SerializeToString,
            ),
            'CallPluginTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallPluginTool,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.CallPluginToolRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.PluginToolExecutionResponse.SerializeToString,
            ),
            'DesktopFocus': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopFocus,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopFocusRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.SerializeToString,
            ),
            'DesktopLocate': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopLocate,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateResponse.SerializeToString,
            ),
            'DesktopClick': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopClick,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopClickRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.SerializeToString,
            ),
            'DesktopDrag': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopDrag,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopDragRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.SerializeToString,
            ),
            'DesktopTypeInto': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopTypeInto,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopTypeIntoRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.SerializeToString,
            ),
            'DesktopAssert': grpc.unary_unary_rpc_method_handler(
                    servicer.DesktopAssert,
                    request_deserializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopAssertRequest.FromString,
                    response_serializer=peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peekaboox.v1.PeekabooX', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('peekaboox.v1.PeekabooX', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeekabooX(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/CaptureScreen',
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureScreenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/CaptureDelta',
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureDeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/CaptureBackends',
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.CaptureBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/MoveMouse',
            peekaboox_dot_v1_dot_peekaboox__pb2.MoveMouseRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/Click',
            peekaboox_dot_v1_dot_peekaboox__pb2.ClickRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/Drag',
            peekaboox_dot_v1_dot_peekaboox__pb2.DragRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/TypeText',
            peekaboox_dot_v1_dot_peekaboox__pb2.TypeTextRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PasteText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/PasteText',
            peekaboox_dot_v1_dot_peekaboox__pb2.PasteTextRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hotkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/Hotkey',
            peekaboox_dot_v1_dot_peekaboox__pb2.HotkeyRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/FindElement',
            peekaboox_dot_v1_dot_peekaboox__pb2.FindElementRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.FindElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/ListWindows',
            peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.ListWindowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDesktopState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/GetDesktopState',
            peekaboox_dot_v1_dot_peekaboox__pb2.GetDesktopStateRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OcrScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/OcrScreen',
            peekaboox_dot_v1_dot_peekaboox__pb2.OcrScreenRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.OcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/CompareImages',
            peekaboox_dot_v1_dot_peekaboox__pb2.CompareImagesRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.VisualDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectUiState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DetectUiState',
            peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiStateRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.UiStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectUiElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DetectUiElements',
            peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DetectUiElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeDmaBuf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/ProbeDmaBuf',
            peekaboox_dot_v1_dot_peekaboox__pb2.ProbeDmaBufRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DmaBufProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/ListPlugins',
            peekaboox_dot_v1_dot_peekaboox__pb2.ListPluginsRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.PluginListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallPluginTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/CallPluginTool',
            peekaboox_dot_v1_dot_peekaboox__pb2.CallPluginToolRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.PluginToolExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopFocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopFocus',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopFocusRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopLocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopLocate',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopLocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopClick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopClick',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopClickRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopDrag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopDrag',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopDragRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopTypeInto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopTypeInto',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopTypeIntoRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesktopAssert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peekaboox.v1.PeekabooX/DesktopAssert',
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopAssertRequest.SerializeToString,
            peekaboox_dot_v1_dot_peekaboox__pb2.DesktopActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
