[package]
name = "peekaboox-vision"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "pnm"] }
peekaboox-capture = { path = "../capture" }
peekaboox-core = { path = "../core" }

[lib]
path = "src/lib.rs"
